services:
  - type: web
    name: nudge
    runtime: node
    buildCommand: npm run render-build
    startCommand: npm run start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
